# Generated by Django 4.0.4 on 2022-05-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_extra_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='extra_images',
            field=models.ManyToManyField(blank=True, null=True, to='product.productimage'),
        ),
    ]
