# Generated by Django 4.0.4 on 2022-05-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_variation_image_remove_variation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_images',
            field=models.ManyToManyField(blank=True, to='product.productimage'),
        ),
    ]
