# Generated by Django 4.0.4 on 2022-05-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_extra_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='extra_images',
        ),
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ImageField(null=True, upload_to='images/variation'),
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
