# Generated by Django 4.0.4 on 2022-05-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_extra_images_variation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
