# Generated by Django 4.0.4 on 2022-05-27 18:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_wishlist_product_wishlist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
