# Generated by Django 4.0.4 on 2022-05-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_variation_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/variation'),
        ),
    ]
