# Generated by Django 4.0.4 on 2022-05-28 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_variation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productadditionalinformation',
            name='variation',
        ),
    ]
