# Generated by Django 3.2.13 on 2022-05-31 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogreview',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.blog'),
        ),
    ]
