# Generated by Django 3.2.13 on 2022-06-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20220601_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='product',
        ),
    ]
