# Generated by Django 3.2.13 on 2022-06-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping_method',
            new_name='shipping_product_type',
        ),
    ]
