# Generated by Django 4.0.5 on 2022-06-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_topdealproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topdealproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='topdealproduct',
            name='product',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
