from django.urls import path

from .views import *


app_name = "product"
urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("product-quick-view/<str:uid>/", FetchProductQuickView.as_view(), name="product-quick-view"),
    path("product-price-on-variation/<str:variation_uid>/<str:product_uid>/", FetchProductPriceOnSingleVariationView.as_view(), name="product-price-on-variation"),
    path("product-price-on-variation/<str:color_uid>/<str:size_uid>/<str:product_uid>/", FetchProductPriceOnMultipleVariationView.as_view(), name="product-price-on-variation"),
    path("add-to-cart/", AddToCartView.as_view(), name="add-to-cart"),
    path("remove-product/", RemoveProductFromCartView.as_view(), name="remove-product"),
    path("add-to-wishlist/", AddToWishlistView.as_view(), name="add-to-wishlist"),
    path("remove-from-wishlist/", RemoveFromWishlistView.as_view(), name="remove-from-wishlist"),
    path("shop/", ShopView.as_view(), name="shop"),
    path("shop/price=<str:filter_min_price>,<str:filter_max_price>/color=<str:color>/size=<str:size>/sort=<str:sort_way>/", ShopFilterProductView.as_view(), name="shop-filter"),
    path("product/category/<str:slug>/price=<str:filter_min_price>,<str:filter_max_price>/color=<str:color>/size=<str:size>/sort=<str:sort_way>/", CategoryWiseFilterProductView.as_view(), name="category-wise-filter"),
    path("product/subcategory/<str:slug>/price=<str:filter_min_price>,<str:filter_max_price>/color=<str:color>/size=<str:size>/sort=<str:sort_way>/", SubategoryWiseFilterProductView.as_view(), name="subcategory-wise-filter"),
    path("product/search/q=<str:search_text>/price=<str:filter_min_price>,<str:filter_max_price>/color=<str:color>/size=<str:size>/sort=<str:sort_way>/", SearchProductFilterView.as_view(), name="search-product-filter"),
    path("product/<str:slug>/", ProductDetailView.as_view(), name="product-detail"),
    path("product-review-submit/", ProductDetailReviewFormSubmitView.as_view(), name="product-review-submit"),
    path("cart/", CartView.as_view(), name="cart"),
    path("update-cartitem/", UpdateCartItemView.as_view(), name="UpdateCartItemView-cart-item"),
    path("apply-promocode/", ApplyPromocodeView.as_view(), name="apply-promocode"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("submit-checkout-form/", SubmitCheckoutFormView.as_view(), name="submit-checkout-form"),
    path("wishlist/", WishlistView.as_view(), name="wishlist"),
    path("blog/", BlogListView.as_view(), name="blog"),
    path("blog/<str:slug>/", BlogDetailView.as_view(), name="blog-detail"),
    path("dashboard/", DashboardAccountView.as_view(), name="dashboard"),
    path("update-account-info/", UpdateAccountInfoView.as_view(), name="update-account-info"),
    path("dashboard/orders/", DashboardOrderView.as_view(), name="dashboard-orders"),
    path("dashboard/order-detail/<str:order_id>/", DashboardOrderDetailView.as_view(), name="dashboard-order-detail"),
    path("dashboard/wishlist/", DashboardWishlistView.as_view(), name="dashboard-wishlist"),
    path("order-received/<str:order_id>/", OrderReceivedView.as_view(), name="order-received"),
    path("track-order/", TrackOrderFormView.as_view(), name="track-order"),
    path("track-order/<str:order_id>/", TrackOrderView.as_view(), name="track-order-detail"),
    path("about-us/", AboutUsView.as_view(), name="about-us"),
    path("contact-us/", ContactUsView.as_view(), name="contact-us"),
    path("product/category/<str:slug>/", CategoryWiseProductView.as_view(), name="category-wise-product"),
    path("product/subcategory/<str:slug>/", SubcategoryWiseProductView.as_view(), name="subcategory-wise-product"),
    path("product/search/q=<str:search_text>/", SearchProductView.as_view(), name="search-product"),
    path("product-auto-search/", ProductAutoSearchView.as_view(), name="product-auto-search"),
    path("blog-auto-search/", BlogAutoSearchView.as_view(), name="blog-auto-search"),
    path("blog/category/<str:slug>/", CategoryWiseBlogView.as_view(), name="category-wise-blog"),
    path("blog/search/q=<str:search_text>/", SearchBlogView.as_view(), name="search-blog"),
    path("submit-blog-comment/", SubmitBlogCommentFormView.as_view(), name="submit-blog-comment"),
]